# Generated by Django 3.2 on 2021-05-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
