# Generated by Django 3.2 on 2021-05-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_approval_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='approval_by',
        ),
    ]
