# Generated by Django 3.2 on 2021-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_approval_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
    ]
