# Generated by Django 3.2 on 2021-05-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_writer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(default=None, max_length=50, verbose_name='email'),
            preserve_default=False,
        ),
    ]
